from selenium import webdriver
import time

Driver = webdriver.Chrome()
Driver.maximize_window()
Driver.get(r"F:/Github/pythonProject/ZDH/frame.html")
time.sleep(1)
Driver.find_element_by_id("input1").send_keys("Hello！ZiSu！")
time.sleep(3)
Driver.get(r"F:/Github/pythonProject/ZDH/autotest.html")
Driver.find_element_by_xpath("//*[@id='accountID']").send_keys("苏尹萱")
Driver.find_element_by_xpath("//*[@id='passwordID']").send_keys("12345637")
Driver.find_element_by_xpath("//*[@id='areaID']").send_keys("北京市")
time.sleep(1)
Driver.find_element_by_xpath("//*[@id='sexID1']").click()
Driver.find_element_by_xpath("//*[@value='spring']").click()
Driver.find_element_by_xpath("//*[@value='summer']").click()
time.sleep(2)
Driver.find_element_by_xpath("//*[@name='file' and @type='file']").send_keys(r"F:\Github\pythonProject\ZDH\头像.jpg")
time.sleep(3)
Driver.get(r"F:/Github/pythonProject/ZDH/dialogs.html")
time.sleep(2)
Driver.find_element_by_xpath("//*[@id='alert']").click()
time.sleep(1)
Driver.switch_to.alert.accept()  # accept()  确定
time.sleep(1)
Driver.find_element_by_xpath("//*[@id='confirm']").click()
time.sleep(1)
Driver.switch_to.alert.dismiss()  # 取消
time.sleep(1)
Driver.find_element_by_xpath("//*[@id='confirm']").click()
time.sleep(1)
Driver.switch_to.alert.accept()  # accept()  确定
time.sleep(3)
Driver.get(r"F:\Github\pythonProject\ZDH\pop.html")
time.sleep(2)
Driver.find_element_by_id("goo").click()
time.sleep(2)
window = Driver.window_handles
Driver.switch_to.window(window[1])
time.sleep(1)
Driver.find_element_by_id("kw").send_keys("京东")
time.sleep(3)
Driver.find_element_by_id("su").click()
time.sleep(3)
Driver.find_element_by_xpath(
    "/html/body/div[1]/div[3]/div[1]/div[3]/div[1]/div/div/div[1]/div/div[1]/div/h2/a[1]").click()
time.sleep(2)
window = Driver.window_handles
Driver.switch_to.window(window[2])
time.sleep(1)
Driver.find_element_by_id("key").send_keys("iPhone13ProMax")
time.sleep(2)
Driver.find_element_by_xpath("//*[@id='search']/div/div[2]/button").click()
time.sleep(2)
Driver.find_element_by_xpath("//*[@id='J_goodsList']/ul/li[1]/div/div[1]/a/img").click()
time.sleep(2)
window = Driver.window_handles
Driver.switch_to.window(window[3])
time.sleep(1)
Driver.find_element_by_xpath("//*[@id='InitCartUrl']").click()
time.sleep(3)
Driver.quit()
